### ISSUE TITLE
Unable to download slave-agent

### ISSUE THREAD

**Issue by cjsfj** [rhwood/jenkins-slave-osx#37]
```
Failing to obtain http://my.jenkins.server.com/computer/opsbibackupsac/slave-agent.jnlp
java.io.IOException: Failed to load http://my.jenkins.server.com/computer/opsbibackupsac/slave-agent.jnlp: 401 Authorization Required
    at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:236)
    at hudson.remoting.Launcher.run(Launcher.java:198)
    at hudson.remoting.Launcher.main(Launcher.java:171)
Waiting 10 seconds before retry
```

Having an issue where the script won't authenticate to pull down the slave-agent.

We are using Jenkins 1.499. I have already implemented the fix outlined in Issue #34. 

Just a quick help in the right direction would be great. Thanks.

**Comment by haysclark** [comment]
@rhwood This issue can be closed as it was resolved.
